
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

.maven: &maven
  image: registry.esss.lu.se/ics-docker/maven:openjdk-11
  tags:
    - docker

stages:
  - compile
  - test
  - package
  - analyse
  - publish

compile:
  <<: *maven
  stage: compile
  script:
    - mvn --batch-mode compile
  artifacts:
    paths:
      - target/
      - xaos.app.module/target/
      - xaos.core.module/target
      - xaos.tests.tools.module/target
      - xaos.tools.module/target
      - xaos.ui.gauge.module/target
      - xaos.ui.module/target
      - xaos.ui.plot.module/target
    expire_in: 1 day

test:
  <<: *maven
  stage: test
  script:
    - /bin/sh -c "xvfb-run -s '-screen 0 1280x1024x16' mvn --batch-mode test"
  timeout: 5 minutes
  artifacts:
    paths:
        - xaos.core.module/target/surefire-reports/TEST-*.xml
        - xaos.tools.module/target/surefire-reports/TEST-*.xml
        - xaos.ui.module/target/surefire-reports/TEST-*.xml
        - xaos.tests.tools.module/target/surefire-reports/TEST-*.xml
    reports:
        junit:
            - xaos.core.module/target/surefire-reports/TEST-*.xml
            - xaos.tools.module/target/surefire-reports/TEST-*.xml
            - xaos.ui.module/target/surefire-reports/TEST-*.xml
            - xaos.tests.tools.module/target/surefire-reports/TEST-*.xml
    
#sonar:
#  stage: analyse
#  <<: *maven
#  script:
#    - mvn -X --batch-mode -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.junit.reportPaths=target/surefire-reports sonar:sonar
#  only:
#    - master

pages:
  stage: publish
  <<: *maven
  script:
    - 'mvn $MAVEN_CLI_OPTS javadoc:aggregate'
    - 'mv target/site/apidocs public'
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
    changes:
      - pom.xml

publish:
  stage: publish
  <<: *maven
  script:
    - mvn --batch-mode -Dxaos.headless=true -DskipTests=true -Dartifactory.username='${ARTIFACTORY_USERNAME}' -Dartifactory.password='${ARTIFACTORY_PASSWORD}' clean deploy
  only:
    - master
