
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - compile
  - test
  - package
  - analyse
  - publish

compile:
  stage: compile
  image: registry.esss.lu.se/ics-docker/maven:openjdk-11
  tags:
    - docker
  script:
    - mvn --batch-mode compile
  artifacts:
    paths:
      - target/
      - xaos.app.module/target/
      - xaos.core.module/target
      - xaos.tests.tools.module/target
      - xaos.tools.module/target
      - xaos.ui.gauge.module/target
      - xaos.ui.module/target
      - xaos.ui.plot.module/target
    expire_in: 1 day

test:
  stage: test
  image: registry.esss.lu.se/ics-docker/maven:openjdk-11
  tags:
    - docker
  script:
    - /bin/sh -c "xvfb-run mvn --batch-mode test"
  artifacts:
    paths:
        - xaos.core.module/target/surefire-reports/TEST-*.xml
        - xaos.tools.module/target/surefire-reports/TEST-*.xml
        - xaos.ui.module/target/surefire-reports/TEST-*.xml
        - xaos.tests.tools.module/target/surefire-reports/TEST-*.xml
    reports:
        junit:
            - xaos.core.module/target/surefire-reports/TEST-*.xml
            - xaos.tools.module/target/surefire-reports/TEST-*.xml
            - xaos.ui.module/target/surefire-reports/TEST-*.xml
            - xaos.tests.tools.module/target/surefire-reports/TEST-*.xml
    
#sonar:
#  stage: analyse
#  image: registry.esss.lu.se/ics-docker/maven:openjdk-11
#  tags:
#    - docker
#  script:
#    - mvn -X --batch-mode -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.junit.reportPaths=target/surefire-reports sonar:sonar
#  only:
#    - master

publish:
  stage: publish
  image: registry.esss.lu.se/ics-docker/maven:openjdk-11
  tags:
    - docker
  script:
    - mvn --batch-mode -Dxaos.headless=true -DskipTests=true -Dartifactory.username='${ARTIFACTORY_USERNAME}' -Dartifactory.password='${ARTIFACTORY_PASSWORD}' clean deploy
  only:
    - master
